apiVersion: v1
kind: Service
metadata:
    name: kgraphql
spec:
    selector:
        app: kgraphql
    ports:
        - port: 80
          targetPort: 3000
    type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: kgraphql
spec:
    replicas: 1
    selector:
        matchLabels:
            app: kgraphql
    template:
        metadata:
            labels:
                app: kgraphql
        spec:
            containers:
                - name: kgraphql
                  image: eyssel/node-express-graphql
                  ports:
                      - containerPort: 3000
                  imagePullPolicy: Always
